%This Matlab code is written to calculate the Mean Square Displacement
%(MSD) and Diffusion coefficient D from particle tracking data. The input
%data is generated by the TrackMate plugin of ImageJ. (doi:10.1038/s41592-022-01507-1)
%The code imports the 'Spots in Tracks statistics' and calculates the MSD
%for the individual Tracks (via separation according to the TrackID). From
%the MSD the Diffusion coefficients are calculated. The evaluation procedure is described elsewhere (doi:10.1016/j.jsb.2005.06.002).
%Before starting please enter the dt that was used during image recording (line 13).

clc;
clear;	% Delete all variables.
imtool close all;	
%define the dt between two frames
dt_in_s=0.04;
% Specify the folder where the files are located.
myFolder='W:\TH-mlab\Mareike Stephan\ParticleTracking\20221012\GUV_15\2ndEvaluation';

%Define the name of the particle tracking data from 'myFolder' that should be loaded
filePattern = fullfile(myFolder,'*Spots in tracks statistics.csv');
theFiles = dir(filePattern);
Line = theFiles;
baseFileName= Line.name;
fullFileName = fullfile(myFolder,baseFileName);
fprintf(1, 'Now reading %s\n', fullFileName);
%read the data
data_raw=csvread(fullFileName,1,2);

%Identify the different tracks via the Track ID
TrackID=data_raw(:,1);
FindTrackID = unique(TrackID); % which will give you the unique elements of A in array B
Ncount = histc(TrackID, FindTrackID); 
%Extract the spot positions from the raw data
predata(:,1)=data_raw(:,3);
predata(:,2)=data_raw(:,4);
kend=length(FindTrackID);
Linear=cell(kend,1);
%Now we start to calculate the MSD for individual Tracks. The individual
%loops (k) correspond to the tracks of different particles
for k=1:kend
    %Select the data for a specific Track ID
ID=FindTrackID(k,1);
N_ID=Ncount(k,1);
IDname=FindTrackID(k,1);
IDstart_position=1+sum(Ncount(1:k-1,1));
IDend_position=IDstart_position+N_ID-1;

data(:,1)=predata(IDstart_position:IDend_position,1);
data(:,2)=predata(IDstart_position:IDend_position,2);
%For the MSD calculation we have to decide how many dt we want to test
nData = size(data,1); %# number of data points
numberOfdeltaT = floor(nData/4); %# for MSD, dt should be up to 1/4 of number of data points
msd = zeros(numberOfdeltaT,3); %# We'll store [mean, std, n]

%# calculate msd for all deltaT's
%https://stackoverflow.com/questions/7489048/calculating-mean-squared-displacement-msd-with-matlab#:~:text=MSD%20is%20defined%20as%20MSD,particle%20over%20time%20interval%20t.
for dt = 1:numberOfdeltaT
   deltaCoords = data(1+dt:end,1:2) - data(1:end-dt,1:2);
   squaredDisplacement = sum(deltaCoords.^2,2); %# dx^2+dy^2
   t=dt.*dt_in_s;
   MSD=mean(squaredDisplacement);
   msd(1+dt,1) = t; %# average
   msd(1+dt,2) = MSD ; %# average
   msd(1+dt,3) = std(squaredDisplacement); %# std
   msd(1+dt,4) = length(squaredDisplacement); %# n
end
%Extract the MSD and dt and plot it (to get the Diffusion coefficient we
%have to plot log (MSD) vs log(dt).

x=msd(2:end,1);
y=msd(2:end,2);
std_msd=msd(2:end,3);

% Fit linear model to data.
Fit = fit(x,y,'poly1');
% yfit = Fit(1)*x+Fit(2);
[fitresult, gof] = fit(x,y,'poly1');
Fit_values=coeffvalues(Fit);
m=Fit_values(1,1);
n=Fit_values(1,2);

% Get the goodness of fit statistics
GOF_Recovery=cell2mat(struct2cell(gof));
sse=GOF_Recovery(1,1);
rsquare=GOF_Recovery(2,1);
dfe=GOF_Recovery(3,1);
adjrsquare=GOF_Recovery(4,1);
rmse=GOF_Recovery(5,1);

%The diffusion coefficient is:
D=m/4;

msd(1,5)=D;

MSDfig=figure();
plot(x,y,'x k')
hold on
grid on;
title({
    ['MEAN SQUARE DISPLACEMENT (Track ID ' num2str(IDname) ')'] 
    ['Equation is y = ' num2str(m) '*x + ' num2str(n)] 
    ['Diffusion coefficient = ' num2str(D) ' µm^2 s^-1  (R^2=' num2str(rsquare) ')']
    });
xlabel('dt [s]');
ylabel('MSD [µm^2]');
hold on
errorbar(x,y,std_msd);
hold on
plot(x,m*x+n,'-. b','LineWidth',1);
hold off
Linear{k}='not linear';

%ask user to continue or stop processing
promptMessage = sprintf('Does the data follow the linear Fit?,\nor Cancel to abort processing?');
button = questdlg(promptMessage, 'Continue', 'Not linear', 'Linear', 'Continue');
if strcmpi(button, 'Linear')
Linear{k,1}='linear';
end

%save the current figure as image:
figure_name = strcat('TrackID_',num2str(IDname),'_MSD_plot');
file_name = strcat(myFolder,'\',figure_name,'.jpg');
exportgraphics(MSDfig,file_name);
%save the MSD data in an excel file
msdName={'dt [s]', 'MSD [µm^2]','sdt MSD','length MSD','Diffusion coefficient [(µm^2)/s]'};
FileName = strcat(myFolder,'\','TrackID_',num2str(IDname),'_MSD_evaluation.xlsx');
writecell(msdName,FileName,'Sheet','Values','Range','A1');
writematrix(msd,FileName,'Sheet','Values','Range','A2');
IDname=FindTrackID(k,1);
Diff(k,1)=IDname;
Diff(k,2)=D;
Diff(k,3)=sse;
Diff(k,4)=rsquare;
Diff(k,5)=dfe;
Diff(k,6)=adjrsquare;
Diff(k,7)=rmse;

clearvars -except Linear and Diff and dt_in_s and k and myFolder and filePattern and theFiles and Line and baseFileName and baseFileName and fullFileName and data_raw and TrackID and FindTrackID and Ncount and predata and predata and kend
close all;
end
%save the Diffusion coefficient data in an excel file
DiffName={'Track ID','Diffusion coefficient [(µm^2)/s]','SSE','Rsquare','dfe','adjrsquare','RMSE','Data behavior'};
DFileName = strcat(myFolder,'\','','Diffusion_coefficients_evaluation.xlsx');
writecell(DiffName,DFileName,'Sheet','Values','Range','A1');
writecell(Linear,DFileName,'Sheet','Values','Range','H2');
writematrix(Diff,DFileName,'Sheet','Values','Range','A2');
clearvars  
close all;	% Close all figure windows created by imtool.
fprintf(1, 'Thanks for this wonderful data :)');